#!/bin/bash
#TODO create File header
#TODO comment

function printUsageText
{
    echo "Usage: ./addDate [-[h|v]] fromFile toFile"
}

# process options
while getopts ":hv" opt; do
    case $opt in
        h  ) echo "This is the help text!";;
        v  ) echo "This is the version text!";;
        \? ) printUsageText
             exit 1
    esac
done
shift $(($OPTIND - 1))

# do the job
fromFile=$1
toFile=$2
if [ -z "$fromFile" ] || [ -z "$toFile" ]; then
    echo "File name missing"
    printUsageText
    exit 1
    #TODO test file for reading and writing rights
else
    tail -n 0 --follow=name $1 | while IFS= read -r line; do
        echo "$(date --iso-8601=seconds) $line";
    done >> $2 &
fi

